# Generated by Django 4.2.8 on 2023-12-18 18:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created date"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modified date"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=1000, verbose_name="description"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("start_time", models.DateTimeField(verbose_name="start_time")),
                ("end_time", models.DateTimeField(verbose_name="end_time")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "reserved_slot",
                "verbose_name_plural": "reserved_slots",
                "ordering": ("start_time",),
            },
        ),
    ]
