# Generated by Django 4.2.8 on 2023-12-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="available_time",
            field=models.IntegerField(
                help_text="Maximum reservation time in minutes",
                verbose_name="available_time",
            ),
        ),
    ]
