# Generated by Django 4.2.8 on 2024-01-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_alter_resource_available_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="location"
            ),
        ),
    ]
