# Generated by Django 4.2.8 on 2023-12-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_name",
            field=models.CharField(
                help_text="Visible name when users go to reserve your resource.",
                max_length=30,
                unique=True,
                verbose_name="public name",
            ),
        ),
    ]
