# Generated by Django 4.2.8 on 2024-01-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_public_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logout",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="logout"
            ),
        ),
    ]
